version: "3.9"
services:
  worker1:
    image: worker
    ports:
      - "1234:1234"
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
    volumes:
      - ~/.aws/:/root/.aws:ro
  worker2:
    image: worker
    ports:
      - "1235:1234"
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
    volumes:
      - ~/.aws/:/root/.aws:ro
  worker3:
    image: worker
    ports:
      - "1236:1234"
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
    volumes:
      - ~/.aws/:/root/.aws:ro
  worker4:
    image: worker
    ports:
      - "1237:1234"
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
    volumes:
      - ~/.aws/:/root/.aws:ro